"""empty message

Revision ID: 141a982b12fe
Revises: f8f283f1a9e1
Create Date: 2026-02-19 04:49:25.845534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141a982b12fe'
down_revision = 'f8f283f1a9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_exam_day'), ['day'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_question_answer1'), ['answer1'])
        batch_op.create_unique_constraint(batch_op.f('uq_question_answer2'), ['answer2'])
        batch_op.create_unique_constraint(batch_op.f('uq_question_answer3'), ['answer3'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_question_answer3'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_question_answer2'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_question_answer1'), type_='unique')
        batch_op.drop_column('correct')

    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_exam_day'), type_='unique')

    op.create_table('question_enrollments',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('solved', sa.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'question_id')
    )
    op.create_table('exam_enrollments',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('exam_id', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.VARCHAR(length=128), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'exam_id')
    )
    # ### end Alembic commands ###
