"""empty message

Revision ID: 262a21c736e2
Revises: a8b277d73723
Create Date: 2026-01-24 15:57:15.288060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262a21c736e2'
down_revision = 'a8b277d73723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verified')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
