"""empty message

Revision ID: 65e14c8bf5eb
Revises: d0abfbcbcbad
Create Date: 2026-01-22 00:40:15.873668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e14c8bf5eb'
down_revision = 'd0abfbcbcbad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('from_school', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('from_school')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
