"""empty message

Revision ID: 82943946bdc6
Revises: b53029722e82
Create Date: 2026-02-20 14:47:47.334310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82943946bdc6'
down_revision = 'b53029722e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('exam_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('exam_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
