"""empty message

Revision ID: a8b277d73723
Revises: 65e14c8bf5eb
Create Date: 2026-01-22 01:51:26.220360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b277d73723'
down_revision = '65e14c8bf5eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=5000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
