"""empty message

Revision ID: b53029722e82
Revises: 141a982b12fe
Create Date: 2026-02-20 13:58:08.259342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53029722e82'
down_revision = '141a982b12fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_question_answer1'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_question_answer2'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_question_answer3'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_question_answer4'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_question_answer4'), ['answer4'])
        batch_op.create_unique_constraint(batch_op.f('uq_question_answer3'), ['answer3'])
        batch_op.create_unique_constraint(batch_op.f('uq_question_answer2'), ['answer2'])
        batch_op.create_unique_constraint(batch_op.f('uq_question_answer1'), ['answer1'])

    # ### end Alembic commands ###
