"""empty message

Revision ID: d0abfbcbcbad
Revises: c487c5aa0563
Create Date: 2026-01-21 17:11:31.275480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0abfbcbcbad'
down_revision = 'c487c5aa0563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('Comments', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('Comments')
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
