"""empty message

Revision ID: e854e5eeb1ec
Revises: a6976636c5c9
Create Date: 2026-01-25 00:47:45.026529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e854e5eeb1ec'
down_revision = 'a6976636c5c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=False))
        batch_op.drop_column('found_place')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('found_place', sa.VARCHAR(length=300), nullable=False))
        batch_op.drop_column('status')
        batch_op.drop_column('place')

    # ### end Alembic commands ###
