"""empty message

Revision ID: f8f283f1a9e1
Revises: d4c524b9de38
Create Date: 2026-02-19 03:06:21.498831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f283f1a9e1'
down_revision = 'd4c524b9de38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer4', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint(None, ['answer4'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('answer4')

    # ### end Alembic commands ###
